### ISSUE TITLE
401 error when using getAccessTokenByEmailPassword function to generate token

### ISSUE THREAD

**Issue by david4599** [webinv/simplysign#1]
Hello,

If I understood the examples you made, it's possible to generate a token from email address and password of a SimplySign account but what is this token ? Is it the 6-digit token to log in the SimplySign Desktop application on Windows like the token generated by the Android and iOS SimplySign app ? 

I tried to use the getAccessTokenByEmailPassword function with my SimplySign account credentials as parameters but it gave me 401 error : 

> Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://model.simplysign.webnotarius.pl/idp/oauth2.0/accessToken` resulted in a `401 401` response: {"timestamp":1551134622972,"status":401,"error":"Unauthorized","message":"No message available","path":"/idp/oauth2.0/ac (truncated...)

I also tried to make the request with a POST request online website but it gave me the same error : 

Headers : 
> {
  "date": "Mon, 25 Feb 2019 22:47:37 GMT",
  "www-authenticate": "Basic realm=\"authentication required\"",
  "transfer-encoding": "chunked",
  "connection": "close",
  "x-xss-protection": "1; mode=block",
  "pragma": "",
  "strict-transport-security": "max-age=63072000; includeSubdomains;, max-age=15768000 ; includeSubDomains",
  "access-control-allow-methods": "GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH",
  "content-type": "application/json;charset=UTF-8, application/json; charset=utf-8",
  "access-control-allow-origin": "*",
  "cache-control": "no-store",
  "access-control-allow-credentials": "false",
  "access-control-allow-headers": "Authorization, Content-Type,Date,Strict-Transport-Security,Cache-Control,Pragma,Expires,Strict-Transport-Security,X-Content-Type-Options,X-XSS-Protection,WWW-Authenticate,Content-Type,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Access-Control-Allow-Credentials,Access-Control-Allow-Methods,Connection,Transfer-Encoding",
  "x-content-type-options": "nosniff",
  "expires": ""
}

Body : 
> {
  "timestamp": 1551134857929,
  "status": 401,
  "error": "Unauthorized",
  "message": "No message available",
  "path": "/idp/oauth2.0/accessToken"
}

And when I enter https://model.simplysign.webnotarius.pl/idp/oauth2.0/accessToken in the browser, an authorization window appeared and asked for a username and a password but what do I have to enter ?

Thanks
David

**Comment by kardasz** [comment]
The `getAccessTokenByEmailPassword` method may not work it depends on your's test env (ask your technical contact).

The most common situation is redirect (oauth 2.0). First you are redirected to `https://dev.simplysign.webnotarius.pl/idp/oauth2.0/authorize?response_type=code&client_id=*****&redirect_uri=http://example.com` where `http://example.com` is allowed `redirect_uri`, you should add your's `redirect_uri` to whitelist in simplysign account (ask your technical contact).

```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
use Webinv\SimplySign\Connection;
use Webinv\SimplySign\Client\Authorization;
$connection = new Connection([
    'client_id' => '**client_id**',
    'client_secret' => '**client_secret**',
    'domain' => Connection::DOMAIN_TEST
]);
$client = new Authorization($connection);
$redirectUrl = 'http://example.com/02-authorization-grant-token.php';
if (isset($_GET['code'])) {
    $token = $client->getAccessTokenByAuthorizationCode($redirectUrl, $_GET['code']);
    print_r($token);
} else {
    header(sprintf('Location: %s', $client->getAuthorizationUrl($redirectUrl)));
}
```
In this example you are redirected to `simplysign` then you have to signin, after successful   authorization you are benign redirected back with url query param `code` which will be exchanged for `access_token` (oauth 2.0).
